
import React,{useEffect,useMemo,useState}from'react';
import{LayoutDashboard,Package,ArrowLeftRight,Users,Wrench,History,Plus,Trash2,Pencil,LogOut,RefreshCw,UserCog,Database}from'lucide-react';

const TABLE='almox_database';
const RECORD='fosso_aod_villares';
const DBKEY='tpcons_almox_v1';
const SUPA_URL='https://qltkepywsfvwwooroit.supabase.co';
const SUPA_KEY='sb_publishable_M7B7NLCNR5RvdNl2oINabw_FK2lUph3';

function hash(v){let h=0,s='TPCONS_'+v;for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return'h_'+Math.abs(h)}
function now(){return new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date())}
function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const g=t=>p.find(x=>x.type===t)?.value;return`${g('year')}-${g('month')}-${g('day')}`}
function br(v){if(!v)return'-';let[y,m,d]=String(v).split('-');return y&&m&&d?`${d}/${m}/${String(y).slice(-2)}`:v}
const users0=[{id:1,nome:'Andre Paulo',login:'admin',senhaHash:hash('admin1'),perfil:'ADMIN',status:'Ativo'},{id:2,nome:'Almoxarife',login:'Almoxarife',senhaHash:hash('fossoaod'),perfil:'EDITOR',status:'Ativo'}];
const obra0={id:1,nomeObra:'CONSTRUÇÃO DO FOSSO AOD',cliente:'VILLARES METALS',status:'Ativa',itemsBase:[],collaborators:[],movements:[]};
function initial(){return{version:Date.now(),updatedAt:now(),updatedBy:'Sistema',users:users0,obras:[obra0]}}
function norm(db){db=db?.obras?db:initial();return{...db,users:db.users?.length?db.users:users0,obras:(db.obras?.length?db.obras:[obra0]).map((o,i)=>({...obra0,...o,id:o.id||Date.now()+i,itemsBase:o.itemsBase||[],collaborators:o.collaborators||[],movements:o.movements||[]}))}}
function local(){let d=JSON.parse(localStorage.getItem(DBKEY)||'null');d=norm(d);localStorage.setItem(DBKEY,JSON.stringify(d));return d}
function saveLocal(db){localStorage.setItem(DBKEY,JSON.stringify(norm(db)))}
async function fetchDb(){try{const r=await fetch(`${SUPA_URL}/rest/v1/${TABLE}?id=eq.${RECORD}&select=data`,{headers:{apikey:SUPA_KEY,Authorization:`Bearer ${SUPA_KEY}`}});if(!r.ok)return null;const j=await r.json();return j?.[0]?.data?norm(j[0].data):null}catch(e){return null}}
async function pushDb(db){try{const r=await fetch(`${SUPA_URL}/rest/v1/${TABLE}?on_conflict=id`,{method:'POST',headers:{apikey:SUPA_KEY,Authorization:`Bearer ${SUPA_KEY}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({id:RECORD,data:norm(db)})});return r.ok}catch(e){return false}}
async function getDb(){const o=await fetchDb();if(o){saveLocal(o);return o}return local()}
function can(u,p){if(!u)return false;if(u.perfil==='ADMIN')return true;return['view','item.create','item.edit','mov.create','mov.edit','col.create','col.edit'].includes(p)}
function saldo(items,movs){return items.map(i=>{let ms=movs.filter(m=>+m.itemId===+i.id),e=ms.filter(m=>m.tipo==='Entrada').reduce((s,m)=>s+ +m.qtd,0),r=ms.filter(m=>m.tipo==='Retirada').reduce((s,m)=>s+ +m.qtd,0),d=ms.filter(m=>m.tipo==='Devolução').reduce((s,m)=>s+ +m.qtd,0),b=ms.filter(m=>['Baixa','Perda'].includes(m.tipo)).reduce((s,m)=>s+ +m.qtd,0),sld=+(i.inicial||0)+e-r+d-b;return{...i,saldo:sld,status:sld<=0?'Sem Estoque':(+i.minimo>0&&sld<=+i.minimo?'Estoque Baixo':'Disponível')}})}
function devolvidos(movs){let o={};movs.filter(m=>m.tipo==='Devolução'&&m.retiradaRefId).forEach(m=>o[m.retiradaRefId]=(o[m.retiradaRefId]||0)+ +m.qtd);return o}
function diff(a,b){if(!a||!b)return 0;return Math.round((new Date(a+'T00:00')-new Date(b+'T00:00'))/86400000)}

export default function App(){const[db,setDb]=useState(local);const[user,setUser]=useState(null);const[obraId,setObraId]=useState(null);const[page,setPage]=useState('Painel');const[msg,setMsg]=useState('');
async function reload(){const d=await getDb();setDb(d);setMsg('ONLINE recarregado em '+now())}
useEffect(()=>{reload();let t=setInterval(reload,5000);window.addEventListener('focus',reload);return()=>{clearInterval(t);window.removeEventListener('focus',reload)}},[]);
async function write(d,by=user?.login||'Sistema'){d=norm({...d,version:Date.now(),updatedAt:now(),updatedBy:by});setDb(d);saveLocal(d);let ok=await pushDb(d);setMsg(ok?'ONLINE salvo em '+now():'Falha ao salvar online. Dados ficaram locais.');let conf=await fetchDb();if(conf){setDb(conf);saveLocal(conf)}}
async function login(login,senha){let d=await getDb();let u=d.users.find(x=>x.login===login&&x.senhaHash===hash(senha)&&x.status!=='Inativo');if(!u)return{error:'Usuário ou senha inválidos'};setDb(d);setUser(u);setObraId(null);return{ok:true}}
if(!user)return<Login onLogin={login}/>;
if(!obraId)return<Obras db={db} user={user} write={write} setObraId={setObraId} logout={()=>setUser(null)} reload={reload} msg={msg}/>;
let obra=db.obras.find(o=>+o.id===+obraId)||db.obras[0];
async function updateObra(p){let base=await getDb();let obras=base.obras.map(o=>+o.id===+obraId?{...o,...p}:o);await write({...base,obras})}
return<Main db={db} obra={obra} user={user} page={page} setPage={setPage} updateObra={updateObra} write={write} logout={()=>setObraId(null)} reload={reload} msg={msg}/>}
function Login({onLogin}){const[l,setL]=useState(''),[s,setS]=useState(''),[m,setM]=useState(''),[load,setLoad]=useState(false);async function go(){setLoad(true);setM('');let r=await onLogin(l,s);if(r?.error)setM(r.error);setLoad(false)}return <div className="login"><div className="login-card"><p className="sub">TPCONS</p><h1>Almoxarifado Online</h1><input placeholder="Usuário" value={l} onChange={e=>setL(e.target.value)}/><input placeholder="Senha" type="password" value={s} onChange={e=>setS(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/>{m&&<p className="err">{m}</p>}<button className="btn" onClick={go}>{load?'Entrando...':'Entrar'}</button><p className="small">admin/admin1 ou Almoxarife/fossoaod</p></div></div>}
function Obras({db,user,write,setObraId,logout,reload,msg}){const[open,setOpen]=useState(false);async function nova(f){await write({...db,obras:[...db.obras,{id:Date.now(),nomeObra:f.nomeObra,cliente:f.cliente,status:f.status,itemsBase:[],collaborators:[],movements:[]}]},user.login);setOpen(false)}return <div className="main" style={{marginLeft:0,width:'100%'}}><div className="row"><div><p className="sub">TPCONS</p><h1 className="title">Selecionar Obra</h1><p className="ok">{msg}</p></div><div className="actions"><button className="btn light" onClick={reload}>Atualizar</button>{user.perfil==='ADMIN'&&<button className="btn" onClick={()=>setOpen(true)}>+ Nova Obra</button>}<button className="btn light" onClick={logout}>Sair</button></div></div><div className="grid cards">{db.obras.map(o=><div className="card" key={o.id}><p className="sub">OBRA</p><h2>{o.nomeObra}</h2><p><b>Cliente:</b> {o.cliente}</p><p><b>Status:</b> {o.status}</p><button className="btn green" onClick={()=>setObraId(o.id)}>Acessar Obra</button></div>)}</div>{open&&<NovaObra onClose={()=>setOpen(false)} onSave={nova}/>}</div>}
function NovaObra({onClose,onSave}){const[f,setF]=useState({nomeObra:'',cliente:'',status:'Ativa'});return <Modal title="Nova Obra" onClose={onClose} onSave={()=>onSave(f)}><Input label="Nome da obra" v={f.nomeObra} set={v=>setF({...f,nomeObra:v})}/><Input label="Cliente" v={f.cliente} set={v=>setF({...f,cliente:v})}/><label className="field">Status<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>Ativa</option><option>Pausada</option><option>Finalizada</option><option>Arquivada</option></select></label></Modal>}
function Main({db,obra,user,page,setPage,updateObra,write,logout,reload,msg}){let items=useMemo(()=>saldo(obra.itemsBase||[],obra.movements||[]),[obra]);let ret=useMemo(()=>devolvidos(obra.movements||[]),[obra]);let pages=[['Painel',LayoutDashboard],['Itens',Package],['Movimentações',ArrowLeftRight],['Colaboradores',Users],['Ferramentas Retidas',Wrench],['Histórico',History],...(user.perfil==='ADMIN'?[['Usuários',UserCog]]:[])];return <div className="layout"><aside className="side"><h3>TPCONS<br/>Almoxarifado</h3><div className="box" style={{background:'#123252',color:'#fff'}}>{user.nome}<br/><span className="pill">{user.perfil}</span></div><button className="btn light" onClick={logout}><LogOut size={16}/> Trocar Obra</button><div className="menu">{pages.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><I size={16}/>{n}</button>)}</div></aside><main className="main"><div className="box row"><div><p className="sub">OBRA ATUAL</p><b>OBRA:</b> {obra.nomeObra}<br/><b>CLIENTE:</b> {obra.cliente}<br/><span className="small">Última sincronização: {db.updatedAt} • {db.updatedBy} • Modo ONLINE SUPABASE</span><p className="ok">{msg}</p></div><button className="btn light" onClick={reload}><RefreshCw size={16}/> Atualizar</button></div>{page==='Painel'&&<Painel items={items} movs={obra.movements||[]}/>} {page==='Itens'&&<Itens items={items} base={obra.itemsBase||[]} updateObra={updateObra} user={user}/>} {page==='Colaboradores'&&<Cols cols={obra.collaborators||[]} movs={obra.movements||[]} updateObra={updateObra} user={user}/>} {page==='Movimentações'&&<Movs items={items} cols={obra.collaborators||[]} movs={obra.movements||[]} updateObra={updateObra} user={user} ret={ret}/>} {page==='Histórico'&&<Movs items={items} cols={obra.collaborators||[]} movs={obra.movements||[]} updateObra={updateObra} user={user} ret={ret}/>} {page==='Ferramentas Retidas'&&<Retidas items={items} cols={obra.collaborators||[]} movs={obra.movements||[]} ret={ret}/>} {page==='Usuários'&&<Usuarios db={db} write={write} user={user}/>}</main></div>}
function Painel({items,movs}){return <><p className="sub">PAINEL</p><h1 className="title">Visão geral do almoxarifado</h1><div className="grid grid6"><Card t="Total" v={items.length}/><Card t="Ferramentas" v={items.filter(i=>i.tipo==='Ferramenta Retornável').length}/><Card t="Materiais" v={items.filter(i=>i.tipo==='Material de Consumo').length}/><Card t="Equipamentos" v={items.filter(i=>i.tipo==='Equipamento').length}/><Card t="Estoque baixo" v={items.filter(i=>i.status==='Estoque Baixo').length}/><Card t="Sem estoque" v={items.filter(i=>i.status==='Sem Estoque').length}/></div><div className="box mt"><h2>Últimas movimentações</h2><Table h={['Data','Tipo','Item','Qtd']}>{movs.slice(-8).reverse().map(m=><tr key={m.id}><td>{br(m.data)}</td><td>{m.tipo}</td><td>{items.find(i=>i.id===m.itemId)?.descricao}</td><td>{m.qtd}</td></tr>)}</Table></div></>}
function Card({t,v}){return <div className="card"><p className="sub">{t}</p><b>{v}</b></div>}
function Header({title,btn,onClick}){return <div className="row"><h1 className="title">{title}</h1>{btn&&<button className="btn" onClick={onClick}><Plus size={16}/>{btn}</button>}</div>}
function Itens({items,base,updateObra,user}){const[open,setOpen]=useState(false),[edit,setEdit]=useState(null);function del(id){updateObra({itemsBase:base.filter(i=>+i.id!==+id)})}return <><Header title="Itens" btn={can(user,'item.create')?'Cadastrar item':null} onClick={()=>{setEdit(null);setOpen(true)}}/><Table h={['Código','Descrição','Tipo','Inicial','Saldo','Status','Ações']}>{items.map(i=><tr key={i.id}><td>{i.codigo}</td><td><b>{i.descricao}</b></td><td>{i.tipo}</td><td>{i.inicial}</td><td><b>{i.saldo} {i.unidade}</b></td><td>{i.status}</td><td><Actions edit={()=>{setEdit(i);setOpen(true)}} del={user.perfil==='ADMIN'?()=>del(i.id):null}/></td></tr>)}</Table>{open&&<ItemModal item={edit} base={base} updateObra={updateObra} onClose={()=>setOpen(false)}/>}</>}
function ItemModal({item,base,updateObra,onClose}){const[f,setF]=useState(item||{tipo:'Ferramenta Retornável',codigo:'',descricao:'',unidade:'UN',inicial:0,minimo:0});function save(){let o={...f,id:item?.id||Date.now(),descricao:String(f.descricao).toUpperCase(),inicial:+f.inicial||0,minimo:+f.minimo||0};updateObra({itemsBase:item?base.map(i=>i.id===item.id?o:i):[...base,o]});onClose()}return <Modal title={item?'Editar item':'Cadastrar item'} onClose={onClose} onSave={save}><Input label="Código" v={f.codigo} set={v=>setF({...f,codigo:v})}/><Input label="Descrição" v={f.descricao} set={v=>setF({...f,descricao:v})}/><Input label="Unidade" v={f.unidade} set={v=>setF({...f,unidade:v})}/><Input label="Estoque inicial" type="number" v={f.inicial} set={v=>setF({...f,inicial:v})}/><Input label="Estoque mínimo" type="number" v={f.minimo} set={v=>setF({...f,minimo:v})}/><label className="field">Tipo<select value={f.tipo} onChange={e=>setF({...f,tipo:e.target.value})}><option>Ferramenta Retornável</option><option>Material de Consumo</option><option>Equipamento</option></select></label></Modal>}
function Cols({cols,movs,updateObra,user}){const[open,setOpen]=useState(false),[edit,setEdit]=useState(null);function del(id){updateObra({collaborators:cols.filter(c=>+c.id!==+id),movements:movs.filter(m=>+m.colaboradorId!==+id&&+m.despachadoPorId!==+id)})}return <><Header title="Colaboradores" btn={can(user,'col.create')?'Novo colaborador':null} onClick={()=>{setEdit(null);setOpen(true)}}/><Table h={['Nome','Função','Matrícula/CPF','Ações']}>{cols.map(c=><tr key={c.id}><td><b>{c.nome}</b></td><td>{c.funcao}</td><td>{c.matricula}</td><td><Actions edit={()=>{setEdit(c);setOpen(true)}} del={user.perfil==='ADMIN'?()=>del(c.id):null}/></td></tr>)}</Table>{open&&<ColModal col={edit} cols={cols} updateObra={updateObra} onClose={()=>setOpen(false)}/>}</>}
function ColModal({col,cols,updateObra,onClose}){const[f,setF]=useState(col||{nome:'',funcao:'',matricula:''});function save(){let o={...f,id:col?.id||Date.now()};updateObra({collaborators:col?cols.map(c=>c.id===col.id?o:c):[...cols,o]});onClose()}return <Modal title={col?'Editar colaborador':'Novo colaborador'} onClose={onClose} onSave={save}><Input label="Nome" v={f.nome} set={v=>setF({...f,nome:v})}/><Input label="Função" v={f.funcao} set={v=>setF({...f,funcao:v})}/><Input label="Matrícula/CPF" v={f.matricula} set={v=>setF({...f,matricula:v})}/></Modal>}
function Movs({items,cols,movs,updateObra,user,ret}){const[open,setOpen]=useState(false),[edit,setEdit]=useState(null);let sorted=[...movs].sort((a,b)=>String(b.data).localeCompare(String(a.data))||b.id-a.id);function del(id){updateObra({movements:movs.filter(m=>+m.id!==+id&&+m.retiradaRefId!==+id)})}return <><Header title="Movimentações" btn={can(user,'mov.create')?'Nova movimentação':null} onClick={()=>{setEdit(null);setOpen(true)}}/><Table h={['Data','Código','Item','Tipo','Qtd','Colaborador','Previsão','Dev. Real','Atraso','Ações']}>{sorted.map(m=>{let i=items.find(x=>x.id===m.itemId),c=cols.find(x=>x.id===m.colaboradorId),rr=movs.find(x=>+x.id===+m.retiradaRefId),prev=m.tipo==='Devolução'?(rr?.previsao||m.previsaoOriginal):m.previsao,atr=m.tipo==='Devolução'&&prev?(diff(m.dataDevolucaoReal,prev)>0?`Atrasou ${diff(m.dataDevolucaoReal,prev)} dia(s)`:'No prazo'):'-';return <tr key={m.id}><td>{br(m.data)}</td><td>{i?.codigo}</td><td><b>{i?.descricao}</b></td><td>{m.tipo}</td><td>{m.qtd}</td><td>{c?.nome||'-'}</td><td>{br(prev)}</td><td>{br(m.dataDevolucaoReal)}</td><td>{atr}</td><td><Actions edit={()=>{setEdit(m);setOpen(true)}} del={user.perfil==='ADMIN'?()=>del(m.id):null}/></td></tr>})}</Table>{open&&<MovModal mov={edit} items={items} cols={cols} movs={movs} updateObra={updateObra} onClose={()=>setOpen(false)} ret={ret}/>}</>}
function MovModal({mov,items,cols,movs,updateObra,onClose,ret}){const[f,setF]=useState(mov||{tipo:'Retirada',data:today(),dataDevolucaoReal:today(),itemId:'',qtd:1,colaboradorId:'',despachadoPorId:'',retiradaRefId:'',previsao:'',obs:''});let pend=movs.filter(m=>m.tipo==='Retirada'&&(+m.qtd-(ret[m.id]||0)>0));function save(){let is=f.tipo==='Devolução',r=movs.find(m=>+m.id===+f.retiradaRefId),o={...f,id:mov?.id||Date.now(),itemId:+f.itemId,qtd:+f.qtd,colaboradorId:f.colaboradorId?+f.colaboradorId:'',despachadoPorId:f.despachadoPorId?+f.despachadoPorId:'',retiradaRefId:is?+f.retiradaRefId:'',dataDevolucaoReal:is?f.dataDevolucaoReal:'',previsao:f.tipo==='Retirada'?f.previsao:'',previsaoOriginal:is?(r?.previsao||''):''};updateObra({movements:mov?movs.map(m=>m.id===mov.id?o:m):[...movs,o]});onClose()}return <Modal title={mov?'Editar movimentação':'Nova movimentação'} onClose={onClose} onSave={save}><label className="field">Tipo<select value={f.tipo} onChange={e=>setF({...f,tipo:e.target.value})}><option>Entrada</option><option>Retirada</option><option>Devolução</option><option>Baixa</option><option>Perda</option></select></label><Input label="Data" type="date" v={f.data} set={v=>setF({...f,data:v})}/>{f.tipo==='Devolução'&&<><Input label="Data devolução real" type="date" v={f.dataDevolucaoReal} set={v=>setF({...f,dataDevolucaoReal:v})}/><label className="field">Retirada em aberto<select value={f.retiradaRefId} onChange={e=>{let r=movs.find(m=>+m.id===+e.target.value);setF({...f,retiradaRefId:e.target.value,itemId:r?.itemId||'',colaboradorId:r?.colaboradorId||'',previsao:r?.previsao||'',qtd:r?(+r.qtd-(ret[r.id]||0)):1})}}><option value="">Selecione</option>{pend.map(p=>{let it=items.find(i=>i.id===p.itemId);return <option key={p.id} value={p.id}>{br(p.data)} - {it?.codigo} {it?.descricao}</option>})}</select></label></>}<label className="field">Item<select value={f.itemId} onChange={e=>setF({...f,itemId:e.target.value})}><option value="">Selecione</option>{items.map(i=><option key={i.id} value={i.id}>{i.codigo} - {i.descricao} | saldo {i.saldo}</option>)}</select></label><Input label="Quantidade" type="number" v={f.qtd} set={v=>setF({...f,qtd:v})}/><label className="field">Colaborador<select value={f.colaboradorId} onChange={e=>setF({...f,colaboradorId:e.target.value})}><option value="">Selecione</option>{cols.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label>{f.tipo==='Retirada'&&<Input label="Previsão devolução" type="date" v={f.previsao} set={v=>setF({...f,previsao:v})}/>}<label className="field">Observações<textarea value={f.obs} onChange={e=>setF({...f,obs:e.target.value})}/></label></Modal>}
function Retidas({items,cols,movs,ret}){let rows=movs.filter(m=>m.tipo==='Retirada').map(m=>{let i=items.find(x=>x.id===m.itemId),c=cols.find(x=>x.id===m.colaboradorId),dev=ret[m.id]||0;return{...m,item:i,col:c,devolvido:dev,saldo:+m.qtd-dev}}).filter(r=>r.saldo>0);return <><Header title="Ferramentas Retidas"/><Table h={['Código','Item','Colaborador','Retirado','Devolvido','Saldo','Data','Previsão','Situação']}>{rows.map(r=><tr key={r.id}><td>{r.item?.codigo}</td><td><b>{r.item?.descricao}</b></td><td>{r.col?.nome}</td><td>{r.qtd}</td><td>{r.devolvido}</td><td><b>{r.saldo}</b></td><td>{br(r.data)}</td><td>{br(r.previsao)}</td><td>{!r.previsao?'Sem prazo':diff(today(),r.previsao)>0?'Atrasada':'No prazo'}</td></tr>)}</Table></>}
function Usuarios({db,write,user}){const[f,setF]=useState({nome:'',login:'',senha:'',perfil:'VISUALIZADOR',status:'Ativo'});function save(){let list=[...db.users,{id:Date.now(),nome:f.nome,login:f.login,senhaHash:hash(f.senha),perfil:f.perfil,status:f.status}];write({...db,users:list},user.login)}return <><Header title="Administração de Usuários"/><div className="box grid grid2"><Input label="Nome" v={f.nome} set={v=>setF({...f,nome:v})}/><Input label="Login" v={f.login} set={v=>setF({...f,login:v})}/><Input label="Senha" type="password" v={f.senha} set={v=>setF({...f,senha:v})}/><label className="field">Perfil<select value={f.perfil} onChange={e=>setF({...f,perfil:e.target.value})}><option>ADMIN</option><option>EDITOR</option><option>VISUALIZADOR</option></select></label><button className="btn" onClick={save}>Criar usuário</button></div><Table h={['Nome','Login','Perfil','Status']}>{db.users.map(u=><tr key={u.id}><td>{u.nome}</td><td>{u.login}</td><td>{u.perfil}</td><td>{u.status}</td></tr>)}</Table></>}
function Actions({edit,del}){return <div className="actions"><button className="btn light" onClick={edit}><Pencil size={14}/></button>{del&&<button className="btn red" onClick={del}><Trash2 size={14}/></button>}</div>}
function Table({h,children}){return <div className="tablewrap"><table><thead><tr>{h.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Modal({title,children,onClose,onSave,saveText='Salvar'}){return <div className="modal"><div className="modal-card"><div className="row"><h1 className="title">{title}</h1><button className="btn light" onClick={onClose}>×</button></div>{children}<div className="actions" style={{justifyContent:'flex-end',marginTop:18}}><button className="btn light" onClick={onClose}>Cancelar</button><button className="btn" onClick={onSave}>{saveText}</button></div></div></div>}
function Input({label,v,set,type='text'}){return <label className="field">{label}<input type={type} value={v||''} onChange={e=>set(e.target.value)}/></label>}
